name: ci

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]

jobs:
  Shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest

    env:
      SHELLCHECK_VERSION: 0.7.1
      SHELLCHECK_PATH: ./shellcheck-latest/shellcheck

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Shellcheck
        run: |
          wget https://github.com/koalaman/shellcheck/releases/download/v${SHELLCHECK_VERSION}/shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz
          tar xf shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz
          mv shellcheck-v${SHELLCHECK_VERSION} shellcheck-latest

      - name: Check scripts
        run: |
          bash -c 'shopt -s globstar; make test'
